package fi.upm.tfg.enums;

/**
 * Created by cherraez on 7/10/13.
 */
public enum Colors {
    BLACKWHITE,
    YELLOWBLUE,
    YELLOWRED,

    BLACKANDWHITE,
    BLACKANDYELLOW,
    WHITEANDBLACK,
    YELLOWANDBLACK,
    WHITEANDBLUE,
    YELLOWANDBLUE,
    BLUEANDWHITE,
    BLUEANDYELLOW,
    WHITEANDRED,
    YELLOWANDRED,
    REDANDWHITE,
    REDANDYELLOW
}
